export const PARENT_SIGNAL_TYPES = {
  ATTENDANCE_LOGGED: "ATTENDANCE_LOGGED",

  XP_MILESTONE: "XP_MILESTONE",

  TESTING_ELIGIBLE: "TESTING_ELIGIBLE",

  TEST_SCHEDULED: "TEST_SCHEDULED",
  TEST_STARTED: "TEST_STARTED",
  TEST_PASSED: "TEST_PASSED",
  TEST_FAILED: "TEST_FAILED",

  COOLDOWN_STARTED: "COOLDOWN_STARTED",
  PREPARATION_WINDOW: "PREPARATION_WINDOW",

  PROMOTED: "PROMOTED",

  COACH_NOTE: "COACH_NOTE",

  FREEZE_WARNING: "FREEZE_WARNING",

  LEVEL_READY: "LEVEL_READY",
} as const;

export type ParentSignalType =
  typeof PARENT_SIGNAL_TYPES[
    keyof typeof PARENT_SIGNAL_TYPES
  ];