export const PARENT_SIGNAL_TYPES = {
  // Daily Activity
  ATTENDANCE_LOGGED: "ATTENDANCE_LOGGED",
  XP_MILESTONE: "XP_MILESTONE",

  // Testing Journey
  TEMPLE_ENTERED: "TEMPLE_ENTERED",
  TESTING_ELIGIBLE: "TESTING_ELIGIBLE",

  TEST_SCHEDULED: "TEST_SCHEDULED",
  TEST_DAY: "TEST_DAY",
  TEST_STARTED: "TEST_STARTED",

  // Successful Path
  TEST_PASSED: "TEST_PASSED",
  COOLDOWN_STARTED: "COOLDOWN_STARTED",
  PROMOTED: "PROMOTED",

  // Retest Path
  TEST_FAILED: "TEST_FAILED",
  TEST_FREEZE: "TEST_FREEZE",
  RETEST_READY: "RETEST_READY",

  // Communication
  COACH_NOTE: "COACH_NOTE",

  // Program Status
  DECAY_WARNING: "DECAY_WARNING",
  DECAY_POINTS: "DECAY_POINTS",
  PROGRAM_FROZEN: "PROGRAM_FROZEN",

  // Accountability
  MINOR_INFRACTION: "MINOR_INFRACTION",
  SEMI_MAJOR_INFRACTION: "SEMI_MAJOR_INFRACTION",
  MAJOR_INFRACTION: "MAJOR_INFRACTION",
} as const;

export type ParentSignalType =
  typeof PARENT_SIGNAL_TYPES[
    keyof typeof PARENT_SIGNAL_TYPES
  ];